version: '3.8'

services:
  # Core Manager
  mcp-manager:
    image: zueai/mcp-manager:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    restart: always
    mem_limit: 256m

  # GCP-oriented Services
  bigquery-mcp:
    image: lucashild/mcp-server-bigquery
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/credentials.json
    volumes:
      - ./secrets:/secrets:ro
    restart: always
    mem_limit: 256m

  gcs-mcp:
    build: ./services/gcs-mcp
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/credentials.json
    volumes:
      - ./secrets:/secrets:ro
    restart: always
    mem_limit: 256m

  # Database servers (minimized for nano VM)
  sqlite-mcp:
    image: modelcontextprotocol/server-sqlite
    volumes:
      - ./data/sqlite:/data
    restart: always
    mem_limit: 128m

  # Search alternative
  search-mcp:
    build: ./services/search-mcp
    environment:
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: always
    mem_limit: 256m

  # Git operations
  git-mcp:
    image: modelcontextprotocol/server-git
    volumes:
      - ./repos:/repos
    restart: always
    mem_limit: 128m

volumes:
  sqlite_data: